### ISSUE TITLE
I want to know where is init_noise from?

### ISSUE THREAD

**Issue by VitoZ-X** [aniki-ly/FreeLong#2]
I want to know where is init_noise from? I search it but not answer
`samples, _, init_noise = ddim_sampler.sample(S=ddim_steps,
                                            conditioning=cond,
                                            batch_size=noise_shape[0],
                                            shape=noise_shape[1:],
                                            verbose=False,
                                            unconditional_guidance_scale=cfg_scale,
                                            unconditional_conditioning=uc,
                                            eta=ddim_eta,
                                            temporal_length=noise_shape[2],
                                            conditional_guidance_scale_temporal=temporal_cfg_scale,
                                            x_T=x_T,
                                            **kwargs
                                            )`

**Comment by aniki-ly** [comment]
The init_noise, which is the input noise for the diffusion model used in SNR calculations, is not utilized in the current code. Please refer to the funcs.py

**Comment by VitoZ-X** [comment]
thank u
